filebeat.inputs:

- type: log

  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/syslog*
    - /var/log/auth.log

#output.elasticsearch:
  #hosts: ["localhost:9200"]

output.logstash:
  hosts: ["localhost:5044"]
  
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s
